scan_filter_chain:
- name: range
  type: LaserScanRangeFilter
  params:
    use_message_range_limits: true
#    lower_threshold: 0.3
#    upper_threshold: .inf
    lower_replacement_value: -.inf
    upper_replacement_value: 21.0
